// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDatasetResult {
    /**
     * @return Dataset description
     * 
     */
    private String description;
    /**
     * @return Dataset identifier
     * 
     */
    private String id;
    /**
     * @return Dataset name
     * 
     */
    private String name;

    private GetDatasetResult() {}
    /**
     * @return Dataset description
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Dataset identifier
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Dataset name
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDatasetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String id;
        private String name;
        public Builder() {}
        public Builder(GetDatasetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetDatasetResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetDatasetResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetDatasetResult", "name");
            }
            this.name = name;
            return this;
        }
        public GetDatasetResult build() {
            final var _resultValue = new GetDatasetResult();
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
