// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNotifierPropertiesEmail {
    /**
     * @return The emails to be notified
     * 
     */
    private List<String> emails;

    private GetNotifierPropertiesEmail() {}
    /**
     * @return The emails to be notified
     * 
     */
    public List<String> emails() {
        return this.emails;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNotifierPropertiesEmail defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> emails;
        public Builder() {}
        public Builder(GetNotifierPropertiesEmail defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.emails = defaults.emails;
        }

        @CustomType.Setter
        public Builder emails(List<String> emails) {
            if (emails == null) {
              throw new MissingRequiredPropertyException("GetNotifierPropertiesEmail", "emails");
            }
            this.emails = emails;
            return this;
        }
        public Builder emails(String... emails) {
            return emails(List.of(emails));
        }
        public GetNotifierPropertiesEmail build() {
            final var _resultValue = new GetNotifierPropertiesEmail();
            _resultValue.emails = emails;
            return _resultValue;
        }
    }
}
