// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetNotifierPropertiesDiscordWebhook {
    /**
     * @return The discord webhook URL
     * 
     */
    private String discordWebhookUrl;

    private GetNotifierPropertiesDiscordWebhook() {}
    /**
     * @return The discord webhook URL
     * 
     */
    public String discordWebhookUrl() {
        return this.discordWebhookUrl;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNotifierPropertiesDiscordWebhook defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String discordWebhookUrl;
        public Builder() {}
        public Builder(GetNotifierPropertiesDiscordWebhook defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.discordWebhookUrl = defaults.discordWebhookUrl;
        }

        @CustomType.Setter
        public Builder discordWebhookUrl(String discordWebhookUrl) {
            if (discordWebhookUrl == null) {
              throw new MissingRequiredPropertyException("GetNotifierPropertiesDiscordWebhook", "discordWebhookUrl");
            }
            this.discordWebhookUrl = discordWebhookUrl;
            return this;
        }
        public GetNotifierPropertiesDiscordWebhook build() {
            final var _resultValue = new GetNotifierPropertiesDiscordWebhook();
            _resultValue.discordWebhookUrl = discordWebhookUrl;
            return _resultValue;
        }
    }
}
