// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class NotifierPropertiesPagerduty {
    /**
     * @return The pagerduty routing key
     * 
     */
    private String routingKey;
    /**
     * @return The pager duty token
     * 
     */
    private String token;

    private NotifierPropertiesPagerduty() {}
    /**
     * @return The pagerduty routing key
     * 
     */
    public String routingKey() {
        return this.routingKey;
    }
    /**
     * @return The pager duty token
     * 
     */
    public String token() {
        return this.token;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NotifierPropertiesPagerduty defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String routingKey;
        private String token;
        public Builder() {}
        public Builder(NotifierPropertiesPagerduty defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.routingKey = defaults.routingKey;
    	      this.token = defaults.token;
        }

        @CustomType.Setter
        public Builder routingKey(String routingKey) {
            if (routingKey == null) {
              throw new MissingRequiredPropertyException("NotifierPropertiesPagerduty", "routingKey");
            }
            this.routingKey = routingKey;
            return this;
        }
        @CustomType.Setter
        public Builder token(String token) {
            if (token == null) {
              throw new MissingRequiredPropertyException("NotifierPropertiesPagerduty", "token");
            }
            this.token = token;
            return this;
        }
        public NotifierPropertiesPagerduty build() {
            final var _resultValue = new NotifierPropertiesPagerduty();
            _resultValue.routingKey = routingKey;
            _resultValue.token = token;
            return _resultValue;
        }
    }
}
