// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class NotifierPropertiesSlack {
    /**
     * @return The slack URL
     * 
     */
    private String slackUrl;

    private NotifierPropertiesSlack() {}
    /**
     * @return The slack URL
     * 
     */
    public String slackUrl() {
        return this.slackUrl;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NotifierPropertiesSlack defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String slackUrl;
        public Builder() {}
        public Builder(NotifierPropertiesSlack defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.slackUrl = defaults.slackUrl;
        }

        @CustomType.Setter
        public Builder slackUrl(String slackUrl) {
            if (slackUrl == null) {
              throw new MissingRequiredPropertyException("NotifierPropertiesSlack", "slackUrl");
            }
            this.slackUrl = slackUrl;
            return this;
        }
        public NotifierPropertiesSlack build() {
            final var _resultValue = new NotifierPropertiesSlack();
            _resultValue.slackUrl = slackUrl;
            return _resultValue;
        }
    }
}
