// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.outputs;

import com.pulumi.core.annotations.CustomType;
import io.gfm.pulumiaxiom.axiom.outputs.NotifierPropertiesDiscord;
import io.gfm.pulumiaxiom.axiom.outputs.NotifierPropertiesDiscordWebhook;
import io.gfm.pulumiaxiom.axiom.outputs.NotifierPropertiesEmail;
import io.gfm.pulumiaxiom.axiom.outputs.NotifierPropertiesOpsgenie;
import io.gfm.pulumiaxiom.axiom.outputs.NotifierPropertiesPagerduty;
import io.gfm.pulumiaxiom.axiom.outputs.NotifierPropertiesSlack;
import io.gfm.pulumiaxiom.axiom.outputs.NotifierPropertiesWebhook;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NotifierProperties {
    private @Nullable NotifierPropertiesDiscord discord;
    private @Nullable NotifierPropertiesDiscordWebhook discordWebhook;
    private @Nullable NotifierPropertiesEmail email;
    private @Nullable NotifierPropertiesOpsgenie opsgenie;
    private @Nullable NotifierPropertiesPagerduty pagerduty;
    private @Nullable NotifierPropertiesSlack slack;
    private @Nullable NotifierPropertiesWebhook webhook;

    private NotifierProperties() {}
    public Optional<NotifierPropertiesDiscord> discord() {
        return Optional.ofNullable(this.discord);
    }
    public Optional<NotifierPropertiesDiscordWebhook> discordWebhook() {
        return Optional.ofNullable(this.discordWebhook);
    }
    public Optional<NotifierPropertiesEmail> email() {
        return Optional.ofNullable(this.email);
    }
    public Optional<NotifierPropertiesOpsgenie> opsgenie() {
        return Optional.ofNullable(this.opsgenie);
    }
    public Optional<NotifierPropertiesPagerduty> pagerduty() {
        return Optional.ofNullable(this.pagerduty);
    }
    public Optional<NotifierPropertiesSlack> slack() {
        return Optional.ofNullable(this.slack);
    }
    public Optional<NotifierPropertiesWebhook> webhook() {
        return Optional.ofNullable(this.webhook);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NotifierProperties defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable NotifierPropertiesDiscord discord;
        private @Nullable NotifierPropertiesDiscordWebhook discordWebhook;
        private @Nullable NotifierPropertiesEmail email;
        private @Nullable NotifierPropertiesOpsgenie opsgenie;
        private @Nullable NotifierPropertiesPagerduty pagerduty;
        private @Nullable NotifierPropertiesSlack slack;
        private @Nullable NotifierPropertiesWebhook webhook;
        public Builder() {}
        public Builder(NotifierProperties defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.discord = defaults.discord;
    	      this.discordWebhook = defaults.discordWebhook;
    	      this.email = defaults.email;
    	      this.opsgenie = defaults.opsgenie;
    	      this.pagerduty = defaults.pagerduty;
    	      this.slack = defaults.slack;
    	      this.webhook = defaults.webhook;
        }

        @CustomType.Setter
        public Builder discord(@Nullable NotifierPropertiesDiscord discord) {

            this.discord = discord;
            return this;
        }
        @CustomType.Setter
        public Builder discordWebhook(@Nullable NotifierPropertiesDiscordWebhook discordWebhook) {

            this.discordWebhook = discordWebhook;
            return this;
        }
        @CustomType.Setter
        public Builder email(@Nullable NotifierPropertiesEmail email) {

            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder opsgenie(@Nullable NotifierPropertiesOpsgenie opsgenie) {

            this.opsgenie = opsgenie;
            return this;
        }
        @CustomType.Setter
        public Builder pagerduty(@Nullable NotifierPropertiesPagerduty pagerduty) {

            this.pagerduty = pagerduty;
            return this;
        }
        @CustomType.Setter
        public Builder slack(@Nullable NotifierPropertiesSlack slack) {

            this.slack = slack;
            return this;
        }
        @CustomType.Setter
        public Builder webhook(@Nullable NotifierPropertiesWebhook webhook) {

            this.webhook = webhook;
            return this;
        }
        public NotifierProperties build() {
            final var _resultValue = new NotifierProperties();
            _resultValue.discord = discord;
            _resultValue.discordWebhook = discordWebhook;
            _resultValue.email = email;
            _resultValue.opsgenie = opsgenie;
            _resultValue.pagerduty = pagerduty;
            _resultValue.slack = slack;
            _resultValue.webhook = webhook;
            return _resultValue;
        }
    }
}
