// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class NotifierPropertiesWebhook {
    /**
     * @return The webhook URL
     * 
     */
    private String url;

    private NotifierPropertiesWebhook() {}
    /**
     * @return The webhook URL
     * 
     */
    public String url() {
        return this.url;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NotifierPropertiesWebhook defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String url;
        public Builder() {}
        public Builder(NotifierPropertiesWebhook defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.url = defaults.url;
        }

        @CustomType.Setter
        public Builder url(String url) {
            if (url == null) {
              throw new MissingRequiredPropertyException("NotifierPropertiesWebhook", "url");
            }
            this.url = url;
            return this;
        }
        public NotifierPropertiesWebhook build() {
            final var _resultValue = new NotifierPropertiesWebhook();
            _resultValue.url = url;
            return _resultValue;
        }
    }
}
