// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package axiom

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/gfmio/pulumi-axiom/sdk/go/axiom/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "axiom:index/dataset:Dataset":
		r = &Dataset{}
	case "axiom:index/monitor:Monitor":
		r = &Monitor{}
	case "axiom:index/notifier:Notifier":
		r = &Notifier{}
	case "axiom:index/user:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:axiom" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"axiom",
		"index/dataset",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"axiom",
		"index/monitor",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"axiom",
		"index/notifier",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"axiom",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"axiom",
		&pkg{version},
	)
}
