// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import io.gfm.pulumiaxiom.Utilities;
import io.gfm.pulumiaxiom.inputs.GetDatasetArgs;
import io.gfm.pulumiaxiom.inputs.GetDatasetPlainArgs;
import io.gfm.pulumiaxiom.inputs.GetMonitorArgs;
import io.gfm.pulumiaxiom.inputs.GetMonitorPlainArgs;
import io.gfm.pulumiaxiom.inputs.GetNotifierArgs;
import io.gfm.pulumiaxiom.inputs.GetNotifierPlainArgs;
import io.gfm.pulumiaxiom.inputs.GetUserArgs;
import io.gfm.pulumiaxiom.inputs.GetUserPlainArgs;
import io.gfm.pulumiaxiom.outputs.GetDatasetResult;
import io.gfm.pulumiaxiom.outputs.GetMonitorResult;
import io.gfm.pulumiaxiom.outputs.GetNotifierResult;
import io.gfm.pulumiaxiom.outputs.GetUserResult;
import java.util.concurrent.CompletableFuture;

public final class AxiomFunctions {
    public static Output<GetDatasetResult> getDataset(GetDatasetArgs args) {
        return getDataset(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetDatasetResult> getDatasetPlain(GetDatasetPlainArgs args) {
        return getDatasetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetDatasetResult> getDataset(GetDatasetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("axiom:index/getDataset:getDataset", TypeShape.of(GetDatasetResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetDatasetResult> getDatasetPlain(GetDatasetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("axiom:index/getDataset:getDataset", TypeShape.of(GetDatasetResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetMonitorResult> getMonitor(GetMonitorArgs args) {
        return getMonitor(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetMonitorResult> getMonitorPlain(GetMonitorPlainArgs args) {
        return getMonitorPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetMonitorResult> getMonitor(GetMonitorArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("axiom:index/getMonitor:getMonitor", TypeShape.of(GetMonitorResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetMonitorResult> getMonitorPlain(GetMonitorPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("axiom:index/getMonitor:getMonitor", TypeShape.of(GetMonitorResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetNotifierResult> getNotifier(GetNotifierArgs args) {
        return getNotifier(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetNotifierResult> getNotifierPlain(GetNotifierPlainArgs args) {
        return getNotifierPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetNotifierResult> getNotifier(GetNotifierArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("axiom:index/getNotifier:getNotifier", TypeShape.of(GetNotifierResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetNotifierResult> getNotifierPlain(GetNotifierPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("axiom:index/getNotifier:getNotifier", TypeShape.of(GetNotifierResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetUserResult> getUser(GetUserArgs args) {
        return getUser(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetUserResult> getUserPlain(GetUserPlainArgs args) {
        return getUserPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetUserResult> getUser(GetUserArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("axiom:index/getUser:getUser", TypeShape.of(GetUserResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetUserResult> getUserPlain(GetUserPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("axiom:index/getUser:getUser", TypeShape.of(GetUserResult.class), args, Utilities.withVersion(options));
    }
}
