// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiAxiom.Axiom.Outputs
{

    [OutputType]
    public sealed class GetNotifierPropertiesResult
    {
        public readonly Outputs.GetNotifierPropertiesDiscordResult Discord;
        public readonly Outputs.GetNotifierPropertiesDiscordWebhookResult DiscordWebhook;
        public readonly Outputs.GetNotifierPropertiesEmailResult Email;
        public readonly Outputs.GetNotifierPropertiesOpsgenieResult Opsgenie;
        public readonly Outputs.GetNotifierPropertiesPagerdutyResult Pagerduty;
        public readonly Outputs.GetNotifierPropertiesSlackResult Slack;
        public readonly Outputs.GetNotifierPropertiesWebhookResult Webhook;

        [OutputConstructor]
        private GetNotifierPropertiesResult(
            Outputs.GetNotifierPropertiesDiscordResult discord,

            Outputs.GetNotifierPropertiesDiscordWebhookResult discordWebhook,

            Outputs.GetNotifierPropertiesEmailResult email,

            Outputs.GetNotifierPropertiesOpsgenieResult opsgenie,

            Outputs.GetNotifierPropertiesPagerdutyResult pagerduty,

            Outputs.GetNotifierPropertiesSlackResult slack,

            Outputs.GetNotifierPropertiesWebhookResult webhook)
        {
            Discord = discord;
            DiscordWebhook = discordWebhook;
            Email = email;
            Opsgenie = opsgenie;
            Pagerduty = pagerduty;
            Slack = slack;
            Webhook = webhook;
        }
    }
}
