// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.gfm.pulumiaxiom.outputs.GetNotifierProperties;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetNotifierResult {
    /**
     * @return Notifier identifier
     * 
     */
    private String id;
    /**
     * @return Notifier name
     * 
     */
    private String name;
    /**
     * @return The properties of the notifier
     * 
     */
    private GetNotifierProperties properties;

    private GetNotifierResult() {}
    /**
     * @return Notifier identifier
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Notifier name
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The properties of the notifier
     * 
     */
    public GetNotifierProperties properties() {
        return this.properties;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNotifierResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String name;
        private GetNotifierProperties properties;
        public Builder() {}
        public Builder(GetNotifierResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.properties = defaults.properties;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNotifierResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetNotifierResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder properties(GetNotifierProperties properties) {
            if (properties == null) {
              throw new MissingRequiredPropertyException("GetNotifierResult", "properties");
            }
            this.properties = properties;
            return this;
        }
        public GetNotifierResult build() {
            final var _resultValue = new GetNotifierResult();
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.properties = properties;
            return _resultValue;
        }
    }
}
