// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetMonitorPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetMonitorPlainArgs Empty = new GetMonitorPlainArgs();

    /**
     * Monitor identifier
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return Monitor identifier
     * 
     */
    public String id() {
        return this.id;
    }

    private GetMonitorPlainArgs() {}

    private GetMonitorPlainArgs(GetMonitorPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMonitorPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMonitorPlainArgs $;

        public Builder() {
            $ = new GetMonitorPlainArgs();
        }

        public Builder(GetMonitorPlainArgs defaults) {
            $ = new GetMonitorPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id Monitor identifier
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetMonitorPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetMonitorPlainArgs", "id");
            }
            return $;
        }
    }

}
