// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.axiom.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetMonitorArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetMonitorArgs Empty = new GetMonitorArgs();

    /**
     * Monitor identifier
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return Monitor identifier
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    private GetMonitorArgs() {}

    private GetMonitorArgs(GetMonitorArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMonitorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMonitorArgs $;

        public Builder() {
            $ = new GetMonitorArgs();
        }

        public Builder(GetMonitorArgs defaults) {
            $ = new GetMonitorArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id Monitor identifier
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id Monitor identifier
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetMonitorArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetMonitorArgs", "id");
            }
            return $;
        }
    }

}
