// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetDatasetArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDatasetArgs Empty = new GetDatasetArgs();

    /**
     * Dataset identifier
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return Dataset identifier
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    private GetDatasetArgs() {}

    private GetDatasetArgs(GetDatasetArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDatasetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDatasetArgs $;

        public Builder() {
            $ = new GetDatasetArgs();
        }

        public Builder(GetDatasetArgs defaults) {
            $ = new GetDatasetArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id Dataset identifier
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id Dataset identifier
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetDatasetArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetDatasetArgs", "id");
            }
            return $;
        }
    }

}
