// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetDatasetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDatasetPlainArgs Empty = new GetDatasetPlainArgs();

    /**
     * Dataset identifier
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return Dataset identifier
     * 
     */
    public String id() {
        return this.id;
    }

    private GetDatasetPlainArgs() {}

    private GetDatasetPlainArgs(GetDatasetPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDatasetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDatasetPlainArgs $;

        public Builder() {
            $ = new GetDatasetPlainArgs();
        }

        public Builder(GetDatasetPlainArgs defaults) {
            $ = new GetDatasetPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id Dataset identifier
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetDatasetPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetDatasetPlainArgs", "id");
            }
            return $;
        }
    }

}
