// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetNotifierArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNotifierArgs Empty = new GetNotifierArgs();

    /**
     * Notifier identifier
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return Notifier identifier
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    private GetNotifierArgs() {}

    private GetNotifierArgs(GetNotifierArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNotifierArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNotifierArgs $;

        public Builder() {
            $ = new GetNotifierArgs();
        }

        public Builder(GetNotifierArgs defaults) {
            $ = new GetNotifierArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id Notifier identifier
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id Notifier identifier
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetNotifierArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetNotifierArgs", "id");
            }
            return $;
        }
    }

}
