// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.gfm.pulumiaxiom.inputs.NotifierPropertiesDiscordArgs;
import io.gfm.pulumiaxiom.inputs.NotifierPropertiesDiscordWebhookArgs;
import io.gfm.pulumiaxiom.inputs.NotifierPropertiesEmailArgs;
import io.gfm.pulumiaxiom.inputs.NotifierPropertiesOpsgenieArgs;
import io.gfm.pulumiaxiom.inputs.NotifierPropertiesPagerdutyArgs;
import io.gfm.pulumiaxiom.inputs.NotifierPropertiesSlackArgs;
import io.gfm.pulumiaxiom.inputs.NotifierPropertiesWebhookArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NotifierPropertiesArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotifierPropertiesArgs Empty = new NotifierPropertiesArgs();

    @Import(name="discord")
    private @Nullable Output<NotifierPropertiesDiscordArgs> discord;

    public Optional<Output<NotifierPropertiesDiscordArgs>> discord() {
        return Optional.ofNullable(this.discord);
    }

    @Import(name="discordWebhook")
    private @Nullable Output<NotifierPropertiesDiscordWebhookArgs> discordWebhook;

    public Optional<Output<NotifierPropertiesDiscordWebhookArgs>> discordWebhook() {
        return Optional.ofNullable(this.discordWebhook);
    }

    @Import(name="email")
    private @Nullable Output<NotifierPropertiesEmailArgs> email;

    public Optional<Output<NotifierPropertiesEmailArgs>> email() {
        return Optional.ofNullable(this.email);
    }

    @Import(name="opsgenie")
    private @Nullable Output<NotifierPropertiesOpsgenieArgs> opsgenie;

    public Optional<Output<NotifierPropertiesOpsgenieArgs>> opsgenie() {
        return Optional.ofNullable(this.opsgenie);
    }

    @Import(name="pagerduty")
    private @Nullable Output<NotifierPropertiesPagerdutyArgs> pagerduty;

    public Optional<Output<NotifierPropertiesPagerdutyArgs>> pagerduty() {
        return Optional.ofNullable(this.pagerduty);
    }

    @Import(name="slack")
    private @Nullable Output<NotifierPropertiesSlackArgs> slack;

    public Optional<Output<NotifierPropertiesSlackArgs>> slack() {
        return Optional.ofNullable(this.slack);
    }

    @Import(name="webhook")
    private @Nullable Output<NotifierPropertiesWebhookArgs> webhook;

    public Optional<Output<NotifierPropertiesWebhookArgs>> webhook() {
        return Optional.ofNullable(this.webhook);
    }

    private NotifierPropertiesArgs() {}

    private NotifierPropertiesArgs(NotifierPropertiesArgs $) {
        this.discord = $.discord;
        this.discordWebhook = $.discordWebhook;
        this.email = $.email;
        this.opsgenie = $.opsgenie;
        this.pagerduty = $.pagerduty;
        this.slack = $.slack;
        this.webhook = $.webhook;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotifierPropertiesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotifierPropertiesArgs $;

        public Builder() {
            $ = new NotifierPropertiesArgs();
        }

        public Builder(NotifierPropertiesArgs defaults) {
            $ = new NotifierPropertiesArgs(Objects.requireNonNull(defaults));
        }

        public Builder discord(@Nullable Output<NotifierPropertiesDiscordArgs> discord) {
            $.discord = discord;
            return this;
        }

        public Builder discord(NotifierPropertiesDiscordArgs discord) {
            return discord(Output.of(discord));
        }

        public Builder discordWebhook(@Nullable Output<NotifierPropertiesDiscordWebhookArgs> discordWebhook) {
            $.discordWebhook = discordWebhook;
            return this;
        }

        public Builder discordWebhook(NotifierPropertiesDiscordWebhookArgs discordWebhook) {
            return discordWebhook(Output.of(discordWebhook));
        }

        public Builder email(@Nullable Output<NotifierPropertiesEmailArgs> email) {
            $.email = email;
            return this;
        }

        public Builder email(NotifierPropertiesEmailArgs email) {
            return email(Output.of(email));
        }

        public Builder opsgenie(@Nullable Output<NotifierPropertiesOpsgenieArgs> opsgenie) {
            $.opsgenie = opsgenie;
            return this;
        }

        public Builder opsgenie(NotifierPropertiesOpsgenieArgs opsgenie) {
            return opsgenie(Output.of(opsgenie));
        }

        public Builder pagerduty(@Nullable Output<NotifierPropertiesPagerdutyArgs> pagerduty) {
            $.pagerduty = pagerduty;
            return this;
        }

        public Builder pagerduty(NotifierPropertiesPagerdutyArgs pagerduty) {
            return pagerduty(Output.of(pagerduty));
        }

        public Builder slack(@Nullable Output<NotifierPropertiesSlackArgs> slack) {
            $.slack = slack;
            return this;
        }

        public Builder slack(NotifierPropertiesSlackArgs slack) {
            return slack(Output.of(slack));
        }

        public Builder webhook(@Nullable Output<NotifierPropertiesWebhookArgs> webhook) {
            $.webhook = webhook;
            return this;
        }

        public Builder webhook(NotifierPropertiesWebhookArgs webhook) {
            return webhook(Output.of(webhook));
        }

        public NotifierPropertiesArgs build() {
            return $;
        }
    }

}
