// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.gfm.pulumiaxiom.inputs.NotifierPropertiesArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NotifierState extends com.pulumi.resources.ResourceArgs {

    public static final NotifierState Empty = new NotifierState();

    /**
     * Notifier name
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Notifier name
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The properties of the notifier
     * 
     */
    @Import(name="properties")
    private @Nullable Output<NotifierPropertiesArgs> properties;

    /**
     * @return The properties of the notifier
     * 
     */
    public Optional<Output<NotifierPropertiesArgs>> properties() {
        return Optional.ofNullable(this.properties);
    }

    private NotifierState() {}

    private NotifierState(NotifierState $) {
        this.name = $.name;
        this.properties = $.properties;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotifierState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotifierState $;

        public Builder() {
            $ = new NotifierState();
        }

        public Builder(NotifierState defaults) {
            $ = new NotifierState(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Notifier name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Notifier name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param properties The properties of the notifier
         * 
         * @return builder
         * 
         */
        public Builder properties(@Nullable Output<NotifierPropertiesArgs> properties) {
            $.properties = properties;
            return this;
        }

        /**
         * @param properties The properties of the notifier
         * 
         * @return builder
         * 
         */
        public Builder properties(NotifierPropertiesArgs properties) {
            return properties(Output.of(properties));
        }

        public NotifierState build() {
            return $;
        }
    }

}
