// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class NotifierPropertiesPagerdutyArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotifierPropertiesPagerdutyArgs Empty = new NotifierPropertiesPagerdutyArgs();

    /**
     * The pagerduty routing key
     * 
     */
    @Import(name="routingKey", required=true)
    private Output<String> routingKey;

    /**
     * @return The pagerduty routing key
     * 
     */
    public Output<String> routingKey() {
        return this.routingKey;
    }

    /**
     * The pager duty token
     * 
     */
    @Import(name="token", required=true)
    private Output<String> token;

    /**
     * @return The pager duty token
     * 
     */
    public Output<String> token() {
        return this.token;
    }

    private NotifierPropertiesPagerdutyArgs() {}

    private NotifierPropertiesPagerdutyArgs(NotifierPropertiesPagerdutyArgs $) {
        this.routingKey = $.routingKey;
        this.token = $.token;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotifierPropertiesPagerdutyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotifierPropertiesPagerdutyArgs $;

        public Builder() {
            $ = new NotifierPropertiesPagerdutyArgs();
        }

        public Builder(NotifierPropertiesPagerdutyArgs defaults) {
            $ = new NotifierPropertiesPagerdutyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param routingKey The pagerduty routing key
         * 
         * @return builder
         * 
         */
        public Builder routingKey(Output<String> routingKey) {
            $.routingKey = routingKey;
            return this;
        }

        /**
         * @param routingKey The pagerduty routing key
         * 
         * @return builder
         * 
         */
        public Builder routingKey(String routingKey) {
            return routingKey(Output.of(routingKey));
        }

        /**
         * @param token The pager duty token
         * 
         * @return builder
         * 
         */
        public Builder token(Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token The pager duty token
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        public NotifierPropertiesPagerdutyArgs build() {
            if ($.routingKey == null) {
                throw new MissingRequiredPropertyException("NotifierPropertiesPagerdutyArgs", "routingKey");
            }
            if ($.token == null) {
                throw new MissingRequiredPropertyException("NotifierPropertiesPagerdutyArgs", "token");
            }
            return $;
        }
    }

}
