// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class NotifierPropertiesSlackArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotifierPropertiesSlackArgs Empty = new NotifierPropertiesSlackArgs();

    /**
     * The slack URL
     * 
     */
    @Import(name="slackUrl", required=true)
    private Output<String> slackUrl;

    /**
     * @return The slack URL
     * 
     */
    public Output<String> slackUrl() {
        return this.slackUrl;
    }

    private NotifierPropertiesSlackArgs() {}

    private NotifierPropertiesSlackArgs(NotifierPropertiesSlackArgs $) {
        this.slackUrl = $.slackUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotifierPropertiesSlackArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotifierPropertiesSlackArgs $;

        public Builder() {
            $ = new NotifierPropertiesSlackArgs();
        }

        public Builder(NotifierPropertiesSlackArgs defaults) {
            $ = new NotifierPropertiesSlackArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param slackUrl The slack URL
         * 
         * @return builder
         * 
         */
        public Builder slackUrl(Output<String> slackUrl) {
            $.slackUrl = slackUrl;
            return this;
        }

        /**
         * @param slackUrl The slack URL
         * 
         * @return builder
         * 
         */
        public Builder slackUrl(String slackUrl) {
            return slackUrl(Output.of(slackUrl));
        }

        public NotifierPropertiesSlackArgs build() {
            if ($.slackUrl == null) {
                throw new MissingRequiredPropertyException("NotifierPropertiesSlackArgs", "slackUrl");
            }
            return $;
        }
    }

}
