// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.gfm.pulumiaxiom.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class NotifierPropertiesWebhookArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotifierPropertiesWebhookArgs Empty = new NotifierPropertiesWebhookArgs();

    /**
     * The webhook URL
     * 
     */
    @Import(name="url", required=true)
    private Output<String> url;

    /**
     * @return The webhook URL
     * 
     */
    public Output<String> url() {
        return this.url;
    }

    private NotifierPropertiesWebhookArgs() {}

    private NotifierPropertiesWebhookArgs(NotifierPropertiesWebhookArgs $) {
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotifierPropertiesWebhookArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotifierPropertiesWebhookArgs $;

        public Builder() {
            $ = new NotifierPropertiesWebhookArgs();
        }

        public Builder(NotifierPropertiesWebhookArgs defaults) {
            $ = new NotifierPropertiesWebhookArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param url The webhook URL
         * 
         * @return builder
         * 
         */
        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url The webhook URL
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        public NotifierPropertiesWebhookArgs build() {
            if ($.url == null) {
                throw new MissingRequiredPropertyException("NotifierPropertiesWebhookArgs", "url");
            }
            return $;
        }
    }

}
