// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface NotifierProperties {
    discord?: pulumi.Input<inputs.NotifierPropertiesDiscord>;
    discordWebhook?: pulumi.Input<inputs.NotifierPropertiesDiscordWebhook>;
    email?: pulumi.Input<inputs.NotifierPropertiesEmail>;
    opsgenie?: pulumi.Input<inputs.NotifierPropertiesOpsgenie>;
    pagerduty?: pulumi.Input<inputs.NotifierPropertiesPagerduty>;
    slack?: pulumi.Input<inputs.NotifierPropertiesSlack>;
    webhook?: pulumi.Input<inputs.NotifierPropertiesWebhook>;
}

export interface NotifierPropertiesDiscord {
    /**
     * The discord channel
     */
    discordChannel: pulumi.Input<string>;
    /**
     * The discord token
     */
    discordToken: pulumi.Input<string>;
}

export interface NotifierPropertiesDiscordWebhook {
    /**
     * The discord webhook URL
     */
    discordWebhookUrl: pulumi.Input<string>;
}

export interface NotifierPropertiesEmail {
    /**
     * The emails to be notified
     */
    emails: pulumi.Input<pulumi.Input<string>[]>;
}

export interface NotifierPropertiesOpsgenie {
    /**
     * The opsgenie API key
     */
    apiKey: pulumi.Input<string>;
    /**
     * The opsgenie is EU
     */
    isEu: pulumi.Input<boolean>;
}

export interface NotifierPropertiesPagerduty {
    /**
     * The pagerduty routing key
     */
    routingKey: pulumi.Input<string>;
    /**
     * The pager duty token
     */
    token: pulumi.Input<string>;
}

export interface NotifierPropertiesSlack {
    /**
     * The slack URL
     */
    slackUrl: pulumi.Input<string>;
}

export interface NotifierPropertiesWebhook {
    /**
     * The webhook URL
     */
    url: pulumi.Input<string>;
}
