// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetNotifierProperties {
    discord: outputs.GetNotifierPropertiesDiscord;
    discordWebhook: outputs.GetNotifierPropertiesDiscordWebhook;
    email: outputs.GetNotifierPropertiesEmail;
    opsgenie: outputs.GetNotifierPropertiesOpsgenie;
    pagerduty: outputs.GetNotifierPropertiesPagerduty;
    slack: outputs.GetNotifierPropertiesSlack;
    webhook: outputs.GetNotifierPropertiesWebhook;
}

export interface GetNotifierPropertiesDiscord {
    /**
     * The discord channel
     */
    discordChannel: string;
    /**
     * The discord token
     */
    discordToken: string;
}

export interface GetNotifierPropertiesDiscordWebhook {
    /**
     * The discord webhook URL
     */
    discordWebhookUrl: string;
}

export interface GetNotifierPropertiesEmail {
    /**
     * The emails to be notified
     */
    emails: string[];
}

export interface GetNotifierPropertiesOpsgenie {
    /**
     * The opsgenie API key
     */
    apiKey: string;
    /**
     * The opsgenie is EU
     */
    isEu: boolean;
}

export interface GetNotifierPropertiesPagerduty {
    /**
     * The pagerduty routing key
     */
    routingKey: string;
    /**
     * The pager duty token
     */
    token: string;
}

export interface GetNotifierPropertiesSlack {
    /**
     * The slack URL
     */
    slackUrl: string;
}

export interface GetNotifierPropertiesWebhook {
    /**
     * The webhook URL
     */
    url: string;
}

export interface NotifierProperties {
    discord?: outputs.NotifierPropertiesDiscord;
    discordWebhook?: outputs.NotifierPropertiesDiscordWebhook;
    email?: outputs.NotifierPropertiesEmail;
    opsgenie?: outputs.NotifierPropertiesOpsgenie;
    pagerduty?: outputs.NotifierPropertiesPagerduty;
    slack?: outputs.NotifierPropertiesSlack;
    webhook?: outputs.NotifierPropertiesWebhook;
}

export interface NotifierPropertiesDiscord {
    /**
     * The discord channel
     */
    discordChannel: string;
    /**
     * The discord token
     */
    discordToken: string;
}

export interface NotifierPropertiesDiscordWebhook {
    /**
     * The discord webhook URL
     */
    discordWebhookUrl: string;
}

export interface NotifierPropertiesEmail {
    /**
     * The emails to be notified
     */
    emails: string[];
}

export interface NotifierPropertiesOpsgenie {
    /**
     * The opsgenie API key
     */
    apiKey: string;
    /**
     * The opsgenie is EU
     */
    isEu: boolean;
}

export interface NotifierPropertiesPagerduty {
    /**
     * The pagerduty routing key
     */
    routingKey: string;
    /**
     * The pager duty token
     */
    token: string;
}

export interface NotifierPropertiesSlack {
    /**
     * The slack URL
     */
    slackUrl: string;
}

export interface NotifierPropertiesWebhook {
    /**
     * The webhook URL
     */
    url: string;
}

