// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiAxiom.Axiom.Inputs
{

    public sealed class NotifierPropertiesOpsgenieGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The opsgenie API key
        /// </summary>
        [Input("apiKey", required: true)]
        public Input<string> ApiKey { get; set; } = null!;

        /// <summary>
        /// The opsgenie is EU
        /// </summary>
        [Input("isEu", required: true)]
        public Input<bool> IsEu { get; set; } = null!;

        public NotifierPropertiesOpsgenieGetArgs()
        {
        }
        public static new NotifierPropertiesOpsgenieGetArgs Empty => new NotifierPropertiesOpsgenieGetArgs();
    }
}
