// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiAxiom.Axiom.Inputs
{

    public sealed class NotifierPropertiesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("discord")]
        public Input<Inputs.NotifierPropertiesDiscordGetArgs>? Discord { get; set; }

        [Input("discordWebhook")]
        public Input<Inputs.NotifierPropertiesDiscordWebhookGetArgs>? DiscordWebhook { get; set; }

        [Input("email")]
        public Input<Inputs.NotifierPropertiesEmailGetArgs>? Email { get; set; }

        [Input("opsgenie")]
        public Input<Inputs.NotifierPropertiesOpsgenieGetArgs>? Opsgenie { get; set; }

        [Input("pagerduty")]
        public Input<Inputs.NotifierPropertiesPagerdutyGetArgs>? Pagerduty { get; set; }

        [Input("slack")]
        public Input<Inputs.NotifierPropertiesSlackGetArgs>? Slack { get; set; }

        [Input("webhook")]
        public Input<Inputs.NotifierPropertiesWebhookGetArgs>? Webhook { get; set; }

        public NotifierPropertiesGetArgs()
        {
        }
        public static new NotifierPropertiesGetArgs Empty => new NotifierPropertiesGetArgs();
    }
}
