// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiAxiom.Axiom.Inputs
{

    public sealed class NotifierPropertiesSlackGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The slack URL
        /// </summary>
        [Input("slackUrl", required: true)]
        public Input<string> SlackUrl { get; set; } = null!;

        public NotifierPropertiesSlackGetArgs()
        {
        }
        public static new NotifierPropertiesSlackGetArgs Empty => new NotifierPropertiesSlackGetArgs();
    }
}
