// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiAxiom.Axiom.Inputs
{

    public sealed class NotifierPropertiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("discord")]
        public Input<Inputs.NotifierPropertiesDiscordArgs>? Discord { get; set; }

        [Input("discordWebhook")]
        public Input<Inputs.NotifierPropertiesDiscordWebhookArgs>? DiscordWebhook { get; set; }

        [Input("email")]
        public Input<Inputs.NotifierPropertiesEmailArgs>? Email { get; set; }

        [Input("opsgenie")]
        public Input<Inputs.NotifierPropertiesOpsgenieArgs>? Opsgenie { get; set; }

        [Input("pagerduty")]
        public Input<Inputs.NotifierPropertiesPagerdutyArgs>? Pagerduty { get; set; }

        [Input("slack")]
        public Input<Inputs.NotifierPropertiesSlackArgs>? Slack { get; set; }

        [Input("webhook")]
        public Input<Inputs.NotifierPropertiesWebhookArgs>? Webhook { get; set; }

        public NotifierPropertiesArgs()
        {
        }
        public static new NotifierPropertiesArgs Empty => new NotifierPropertiesArgs();
    }
}
