// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiAxiom.Axiom.Inputs
{

    public sealed class NotifierPropertiesPagerdutyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The pagerduty routing key
        /// </summary>
        [Input("routingKey", required: true)]
        public Input<string> RoutingKey { get; set; } = null!;

        /// <summary>
        /// The pager duty token
        /// </summary>
        [Input("token", required: true)]
        public Input<string> Token { get; set; } = null!;

        public NotifierPropertiesPagerdutyGetArgs()
        {
        }
        public static new NotifierPropertiesPagerdutyGetArgs Empty => new NotifierPropertiesPagerdutyGetArgs();
    }
}
