// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDataset(args: GetDatasetArgs, opts?: pulumi.InvokeOptions): Promise<GetDatasetResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("axiom:index/getDataset:getDataset", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getDataset.
 */
export interface GetDatasetArgs {
    /**
     * Dataset identifier
     */
    id: string;
}

/**
 * A collection of values returned by getDataset.
 */
export interface GetDatasetResult {
    /**
     * Dataset description
     */
    readonly description: string;
    /**
     * Dataset identifier
     */
    readonly id: string;
    /**
     * Dataset name
     */
    readonly name: string;
}
export function getDatasetOutput(args: GetDatasetOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDatasetResult> {
    return pulumi.output(args).apply((a: any) => getDataset(a, opts))
}

/**
 * A collection of arguments for invoking getDataset.
 */
export interface GetDatasetOutputArgs {
    /**
     * Dataset identifier
     */
    id: pulumi.Input<string>;
}
