// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNotifier(args: GetNotifierArgs, opts?: pulumi.InvokeOptions): Promise<GetNotifierResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("axiom:index/getNotifier:getNotifier", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getNotifier.
 */
export interface GetNotifierArgs {
    /**
     * Notifier identifier
     */
    id: string;
}

/**
 * A collection of values returned by getNotifier.
 */
export interface GetNotifierResult {
    /**
     * Notifier identifier
     */
    readonly id: string;
    /**
     * Notifier name
     */
    readonly name: string;
    /**
     * The properties of the notifier
     */
    readonly properties: outputs.GetNotifierProperties;
}
export function getNotifierOutput(args: GetNotifierOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetNotifierResult> {
    return pulumi.output(args).apply((a: any) => getNotifier(a, opts))
}

/**
 * A collection of arguments for invoking getNotifier.
 */
export interface GetNotifierOutputArgs {
    /**
     * Notifier identifier
     */
    id: pulumi.Input<string>;
}
